services:
  - type: web
    name: smart-attendance-system
    env: python
    buildCommand: "pip install --upgrade pip && pip install cmake dlib && pip install -r requirements.txt"
    startCommand: "python web/wsgi.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 8000
