services:
  - type: web
    name: smart-attendance-system
    env: python
    buildCommand: "pip install -r requirements-deploy.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 2 web.app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
